<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Features\CQRS\Handlers\AuthHandlers\WriteHandlers\RegisterCommandHandler1.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="12.0.1" />
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.1" />
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="MediatR" Version="14.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NTierArchTestProject.DataAccessLayer\NTierArchTestProject.DataAccessLayer.csproj" />
  </ItemGroup>

</Project>
